### <u>***UNIDAD 1. DESCARGAR BASES DE DATOS E INFORMACION BASICA DE LA BASE DE DATOS***</u>

Pandas es la librería más popular de Python para el análisis de datos.

En Pandas, hay dos objetos principales: el ***DataFrame*** y la ***Serie***.

Un ***DataFrame*** es una tabla. Contiene un array de entradas individuales, cada una de las cuales tiene un valor determinado. Cada entrada corresponde a una fila (o registro) y a una columna. Al final es como una tabla de una base de datos.

In [ ]:
# Importamos la librería de Pandas

import pandas as pd

A continuación, creamos un dataframe a partir de un archivo de excel, usando un método de Pandas llamado <code>read_csv()</code>. El primer parámetro es el nombre del archivo del que vamos a leer, y el segundo parámetro se indica para eliminar la columna de indice que por defecto nos da un dataframe.

Podeis realizar vuestras pruebas quitando y poniendo parámetros.

Mas info en la web de [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)


---

In [ ]:
# (Descargar archivo del projecto de Github)

df=pd.read_csv('Advertising.csv', index_col=0)
df

        TV  Radio  Newspaper  Sales
1    230.1   37.8       69.2   22.1
2     44.5   39.3       45.1   10.4
3     17.2   45.9       69.3    9.3
4    151.5   41.3       58.5   18.5
5    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
196   38.2    3.7       13.8    7.6
197   94.2    4.9        8.1    9.7
198  177.0    9.3        6.4   12.8
199  283.6   42.0       66.2   25.5
200  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

Creamos otro dataframe a partir de un archivo csv utilizando, de nuevo, el método de Pandas <code>read_csv()</code>.

También podemos leer de otros muchos tipos de archivos (*excel, json, sql, html, xml, sas, etc...*), para crear un dataframe.

Mas info en [Pandas](https://pandas.pydata.org/docs/reference/io.html)

In [ ]:
# (Descargar archivo del projecto de Github)

df= pd.read_csv('ds_salaries.csv')

df



---



Para ver el numero de filas y columnas usamos la propiedad de Pandas <code>shape</code>

In [ ]:
df.shape

(200, 4)



---


Podemos ver el dataframe completo usando el método <code>to_string()</code>.

Este método muestra un DataFrame en una salida tabular amigable para la consola.

In [ ]:
# Para poder ver la DF completa usamos el método to_string()

print(df.to_string())

        TV  Radio  Newspaper  Sales
1    230.1   37.8       69.2   22.1
2     44.5   39.3       45.1   10.4
3     17.2   45.9       69.3    9.3
4    151.5   41.3       58.5   18.5
5    180.8   10.8       58.4   12.9
6      8.7   48.9       75.0    7.2
7     57.5   32.8       23.5   11.8
8    120.2   19.6       11.6   13.2
9      8.6    2.1        1.0    4.8
10   199.8    2.6       21.2   10.6
11    66.1    5.8       24.2    8.6
12   214.7   24.0        4.0   17.4
13    23.8   35.1       65.9    9.2
14    97.5    7.6        7.2    9.7
15   204.1   32.9       46.0   19.0
16   195.4   47.7       52.9   22.4
17    67.8   36.6      114.0   12.5
18   281.4   39.6       55.8   24.4
19    69.2   20.5       18.3   11.3
20   147.3   23.9       19.1   14.6
21   218.4   27.7       53.4   18.0
22   237.4    5.1       23.5   12.5
23    13.2   15.9       49.6    5.6
24   228.3   16.9       26.2   15.5
25    62.3   12.6       18.3    9.7
26   262.9    3.5       19.5   12.0
27   142.9   29.3       12.6   15.0
28   240.1   16.7       22.9   15.9
29   248.8   27.1       22.9   18.9
30    70.6   16.0       40.8   10.5
31   292.9   28.3       43.2   21.4
32   112.9   17.4       38.6   11.9
33    97.2    1.5       30.0    9.6
34   265.6   20.0        0.3   17.4
35    95.7    1.4        7.4    9.5
36   290.7    4.1        8.5   12.8
37   266.9   43.8        5.0   25.4
38    74.7   49.4       45.7   14.7
39    43.1   26.7       35.1   10.1
40   228.0   37.7       32.0   21.5
41   202.5   22.3       31.6   16.6
42   177.0   33.4       38.7   17.1
43   293.6   27.7        1.8   20.7
44   206.9    8.4       26.4   12.9
45    25.1   25.7       43.3    8.5
46   175.1   22.5       31.5   14.9
47    89.7    9.9       35.7   10.6
48   239.9   41.5       18.5   23.2
49   227.2   15.8       49.9   14.8
50    66.9   11.7       36.8    9.7
51   199.8    3.1       34.6   11.4
52   100.4    9.6        3.6   10.7
53   216.4   41.7       39.6   22.6
54   182.6   46.2       58.7   21.2
55   262.7   28.8       15.9   20.2
56   198.9   49.4       60.0   23.7
57     7.3   28.1       41.4    5.5
58   136.2   19.2       16.6   13.2
59   210.8   49.6       37.7   23.8
60   210.7   29.5        9.3   18.4
61    53.5    2.0       21.4    8.1
62   261.3   42.7       54.7   24.2
63   239.3   15.5       27.3   15.7
64   102.7   29.6        8.4   14.0
65   131.1   42.8       28.9   18.0
66    69.0    9.3        0.9    9.3
67    31.5   24.6        2.2    9.5
68   139.3   14.5       10.2   13.4
69   237.4   27.5       11.0   18.9
70   216.8   43.9       27.2   22.3
71   199.1   30.6       38.7   18.3
72   109.8   14.3       31.7   12.4
73    26.8   33.0       19.3    8.8
74   129.4    5.7       31.3   11.0
75   213.4   24.6       13.1   17.0
76    16.9   43.7       89.4    8.7
77    27.5    1.6       20.7    6.9
78   120.5   28.5       14.2   14.2
79     5.4   29.9        9.4    5.3
80   116.0    7.7       23.1   11.0
81    76.4   26.7       22.3   11.8
82   239.8    4.1       36.9   12.3
83    75.3   20.3       32.5   11.3
84    68.4   44.5       35.6   13.6
85   213.5   43.0       33.8   21.7
86   193.2   18.4       65.7   15.2
87    76.3   27.5       16.0   12.0
88   110.7   40.6       63.2   16.0
89    88.3   25.5       73.4   12.9
90   109.8   47.8       51.4   16.7
91   134.3    4.9        9.3   11.2
92    28.6    1.5       33.0    7.3
93   217.7   33.5       59.0   19.4
94   250.9   36.5       72.3   22.2
95   107.4   14.0       10.9   11.5
96   163.3   31.6       52.9   16.9
97   197.6    3.5        5.9   11.7
98   184.9   21.0       22.0   15.5
99   289.7   42.3       51.2   25.4
100  135.2   41.7       45.9   17.2
101  222.4    4.3       49.8   11.7
102  296.4   36.3      100.9   23.8
103  280.2   10.1       21.4   14.8
104  187.9   17.2       17.9   14.7
105  238.2   34.3        5.3   20.7
106  137.9   46.4       59.0   19.2
107   25.0   11.0       29.7    7.2
108   90.4    0.3       23.2    8.7
109   13.1    0.4       25.6    5.3
110  255.4   26.9        5.5   19.8
111  225.8    8.2       56.5   13.4
112  241.7   38.0       23.2   21.8
113  175.7   15.4        2.4   14.1
114  209.6   20.6       10.7   15.9
115   78.2   46.8       34.5   14.6
116   75.1   35.0       52.7   12.6
117  139.2   14.3       25.6   12.2
118   76.4    0.8       14.8    9.4
119  125.7   36.9       79.2   15.9
120   19.4   16.0       22.3    6.6
121  141.3   26.8       46.2   15.5
122   18.8   21.7       50.4    7.0
123  224.0    2.4       15.6   11.6
124  123.1   34.6       12.4   15.2
125  229.5   32.3       74.2   19.7
126   87.2   11.8       25.9   10.6
127    7.8   38.9       50.6    6.6
128   80.2    0.0        9.2    8.8
129  220.3   49.0        3.2   24.7
130   59.6   12.0       43.1    9.7
131    0.7   39.6        8.7    1.6
132  265.2    2.9       43.0   12.7
133    8.4   27.2        2.1    5.7
134  219.8   33.5       45.1   19.6
135   36.9   38.6       65.6   10.8
136   48.3   47.0        8.5   11.6
137   25.6   39.0        9.3    9.5
138  273.7   28.9       59.7   20.8
139   43.0   25.9       20.5    9.6
140  184.9   43.9        1.7   20.7
141   73.4   17.0       12.9   10.9
142  193.7   35.4       75.6   19.2
143  220.5   33.2       37.9   20.1
144  104.6    5.7       34.4   10.4
145   96.2   14.8       38.9   11.4
146  140.3    1.9        9.0   10.3
147  240.1    7.3        8.7   13.2
148  243.2   49.0       44.3   25.4
149   38.0   40.3       11.9   10.9
150   44.7   25.8       20.6   10.1
151  280.7   13.9       37.0   16.1
152  121.0    8.4       48.7   11.6
153  197.6   23.3       14.2   16.6
154  171.3   39.7       37.7   19.0
155  187.8   21.1        9.5   15.6
156    4.1   11.6        5.7    3.2
157   93.9   43.5       50.5   15.3
158  149.8    1.3       24.3   10.1
159   11.7   36.9       45.2    7.3
160  131.7   18.4       34.6   12.9
161  172.5   18.1       30.7   14.4
162   85.7   35.8       49.3   13.3
163  188.4   18.1       25.6   14.9
164  163.5   36.8        7.4   18.0
165  117.2   14.7        5.4   11.9
166  234.5    3.4       84.8   11.9
167   17.9   37.6       21.6    8.0
168  206.8    5.2       19.4   12.2
169  215.4   23.6       57.6   17.1
170  284.3   10.6        6.4   15.0
171   50.0   11.6       18.4    8.4
172  164.5   20.9       47.4   14.5
173   19.6   20.1       17.0    7.6
174  168.4    7.1       12.8   11.7
175  222.4    3.4       13.1   11.5
176  276.9   48.9       41.8   27.0
177  248.4   30.2       20.3   20.2
178  170.2    7.8       35.2   11.7
179  276.7    2.3       23.7   11.8
180  165.6   10.0       17.6   12.6
181  156.6    2.6        8.3   10.5
182  218.5    5.4       27.4   12.2
183   56.2    5.7       29.7    8.7
184  287.6   43.0       71.8   26.2
185  253.8   21.3       30.0   17.6
186  205.0   45.1       19.6   22.6
187  139.5    2.1       26.6   10.3
188  191.1   28.7       18.2   17.3
189  286.0   13.9        3.7   15.9
190   18.7   12.1       23.4    6.7
191   39.5   41.1        5.8   10.8
192   75.5   10.8        6.0    9.9
193   17.2    4.1       31.6    5.9
194  166.8   42.0        3.6   19.6
195  149.7   35.6        6.0   17.3
196   38.2    3.7       13.8    7.6
197   94.2    4.9        8.1    9.7
198  177.0    9.3        6.4   12.8
199  283.6   42.0       66.2   25.5
200  232.1    8.6        8.7   13.4



---


Para ver mas informacion usamos el método de Pandas <code>info()</code> esta vez va con parentesis porque es una funcion (metodo).

> *Recordemos que los métodos son funciones que pertenecen a una clase.*


Los *object* que se ven en la columna de "tipos de datos" (Dtype) son *strings*

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 200 entries, 1 to 200
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 7.8 KB



---



El método de Pandas <code>head()</code> muestra el número de filas que queremos visualizar desde el principio (cabecera) del dataframe (df), pasándole el número de filas como parámetro de la función. Si no se indica el número de filas en el método, muestra las 5 primeras filas por defecto.

Más info en [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html#pandas.DataFrame.head).

In [ ]:
# Nos muestra las 20 primeras filas del dataframe.

df.head(15)

       TV  Radio  Newspaper  Sales
1   230.1   37.8       69.2   22.1
2    44.5   39.3       45.1   10.4
3    17.2   45.9       69.3    9.3
4   151.5   41.3       58.5   18.5
5   180.8   10.8       58.4   12.9
6     8.7   48.9       75.0    7.2
7    57.5   32.8       23.5   11.8
8   120.2   19.6       11.6   13.2
9     8.6    2.1        1.0    4.8
10  199.8    2.6       21.2   10.6
11   66.1    5.8       24.2    8.6
12  214.7   24.0        4.0   17.4
13   23.8   35.1       65.9    9.2
14   97.5    7.6        7.2    9.7
15  204.1   32.9       46.0   19.0



---



El método de Pandas <code>tail()</code> muestra el número de filas que queremos visualizar desde el final (cola) del dataframe (df), pasándole el número de filas como parámetro de la función. Si no se indica el número de filas en el método, muestra las 5 últimas filas por defecto.

Más info en [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.tail.html#pandas.DataFrame.tail).

In [ ]:
# Nos muestra las 15 ultimas filas del dataframe.

df.tail(15)



---



Pandas tiene un sistema de opciones que permite personalizar algunos aspectos de su comportamiento, siendo las opciones relacionadas con la visualización las que el usuario es más propenso a ajustar.

Esto lo conseguimos con el método <code>set_option()</code>.

En el siguiente snippet, cambiamos la opción de visualización máxima de columnas a 11.

Más info en [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.set_option.html#pandas-set-option).

In [ ]:
pd.set_option('display.max_columns', 11)

In [ ]:
df



---



La función <code>describe()</code> genera estadísticas descriptivas del dataframe, como la media (**mean**), la desviación estándar (**std**), los porcentiles (**25%, 50% y 75%**), el valor mínimo (**min**) y el valor máximo (**max**), además del recuento (**count**) de todos los valores de cada columna (excluyendo los valores NaN, es decir, aquellos valores que no son númericos).

In [ ]:
df.describe()
# round(df.describe(),2) ---> Redondeamos los valores estadísticos a 2 decimales.

               TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

### <u>***UNIDAD 2: DATAFRAME Y SERIES***</u>



---

Anteriomente, vimos la definición de un dataframe. Una **Serie**, por el contrario, e**s una secuencia de valores de datos**.

> ***Si un DataFrame es una tabla, una Serie es una lista.***

Podemos crear un dataframe desde cero, mediante los ***diccionarios*** de Python.

Recordemos que un diccionario es una estructura de datos de Python donde se almacenan pares de Clave-Valor, separados por dos puntos (:), y cada par separado por comas.

A continuación, vamos a ver diferentes formas de crear el diccionario:

In [ ]:
# Usando un diccionario básico tenemos
gente= {
    'nombre':'Marta',
    'apellido': 'Ruiz',
    'email': 'martaruiz@gmail.com'
}

In [ ]:
# Diccionario con listas de una sola persona
gente={
    'nombre': ['Marta'],
    'apellido': ['Ruiz'],
    'email': ['martaruiz@gmail.com']
}

In [ ]:
# Diccionario con listas de varias personas
gente={
    'nombre': ['Marta', 'Luis', 'Ana'],
    'apellido': ['Ruiz', 'Lopez', 'Santana'],
    'email': ['martaruiz@gmail.com', 'luislopez@gmail.com', 'anasantana@gmail.com']
}

In [ ]:
# imprimimos los valores de la clave "email"

gente['email']

['martaruiz@gmail.com', 'luislopez@gmail.com', 'anasantana@gmail.com']



---


Para crear un dataframe con el diccionario anterior usamos el constructor de Pandas <code>pd.Dataframe()</code> ("pd" es el alias que hemos puesto al importar la librería de Pandas), y le pasamos como parámetro el diccionario.

Más info en [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html).

In [ ]:
df=pd.DataFrame(gente)

df

  nombre apellido                 email
0  Marta     Ruiz   martaruiz@gmail.com
1   Luis    Lopez   luislopez@gmail.com
2    Ana  Santana  anasantana@gmail.com

In [ ]:
# Para acceder a informacion y ver los indices

df['email']

0     martaruiz@gmail.com
1     luislopez@gmail.com
2    anasantana@gmail.com
Name: email, dtype: object

In [ ]:
# También podemos acceder a la información de una columna de la siguiente manera:

df.email

0     martaruiz@gmail.com
1     luislopez@gmail.com
2    anasantana@gmail.com
Name: email, dtype: object



---



Cuando pedimos que nos diga el tipo (type) de una columna de un dataframe, vemos que lo que nos devuelve es una *Serie*.

In [ ]:
type(df['email'])

pandas.core.series.Series



---


Si queremos acceder a varias columnas, hace falta el doble corchete para evitar que pandas piense que los dos strings son el nombre de una sola
columna

In [ ]:
df[['apellido', 'email']]

  apellido                 email
0     Ruiz   martaruiz@gmail.com
1    Lopez   luislopez@gmail.com
2  Santana  anasantana@gmail.com



---


Para acceder a los nombres de las columnas podemos usar la propiedad de Pandas <code>columns</code>

In [ ]:
df.columns

Index(['nombre', 'apellido', 'email'], dtype='object')



---


La indexación en Pandas funciona en uno de los dos siguientes paradigmas:
*   Selección basada en índices.
*   Selección basada en etiquetas.

La selección basada en índices selecciona los datos basándose en su posición numérica en el dataframe. La propiedad <code>iloc</code> sigue este paradigma.

In [ ]:
# Para ver las filas usamos los indices y la funcion iloc y la notación de
# índices (integer location)

df.iloc[0]

nombre                    Marta
apellido                   Ruiz
email       martaruiz@gmail.com
Name: 0, dtype: object

In [ ]:
# Si queremos ver dos filas usamos una lista numérica dentro de la notación
# de índices

df.iloc[[0,2]]

  nombre apellido                 email
0  Marta     Ruiz   martaruiz@gmail.com
2    Ana  Santana  anasantana@gmail.com

In [ ]:
# Si queremos mostrar dos filas y la columna con el indice 2

df.iloc[[0, 1], 2]

0    martaruiz@gmail.com
1    luislopez@gmail.com
Name: email, dtype: object



---


En el paradigma de la selección basada en etiquetas lo que importa es el valor del índice del dato, no su posición.

<code>iloc</code> es conceptualmente más sencillo que <code>loc</code> porque ignora los índices del conjunto de datos. Cuando usamos <code>iloc</code> tratamos el conjunto de datos como una gran matriz (una lista de listas), en la que tenemos que indexar por posición.

<code>loc</code>, por el contrario, usa la información de los índices para hacer su trabajo. Dado que el conjunto de datos suele tener índices significativos, suele ser más fácil hacer las cosas con <code>loc</code>.

In [ ]:
# Mostramos otra vez nuestra tabla o DataFrame

df

  nombre apellido                 email
0  Marta     Ruiz   martaruiz@gmail.com
1   Luis    Lopez   luislopez@gmail.com
2    Ana  Santana  anasantana@gmail.com

In [ ]:
# Accedemos a datos del primer registro igual que hacíamos con iloc.

df.loc[0]

nombre                    Marta
apellido                   Ruiz
email       martaruiz@gmail.com
Name: 0, dtype: object

In [ ]:
# Podemos acceder a unos registros (filas) concretas del dataframe
# y a unas columnas concretas, de la siguiente manera:

df.loc[[0,1], ['email', 'apellido']]

                 email apellido
0  martaruiz@gmail.com     Ruiz
1  luislopez@gmail.com    Lopez

In [ ]:
# También podemos usar el slicing o loncheado de la notación de índices.
# No hay doble corchete porque no estamos pasando una lista como antes.

df.loc[0:2, 'email']

0     martaruiz@gmail.com
1     luislopez@gmail.com
2    anasantana@gmail.com
Name: email, dtype: object

In [ ]:
# Igualmente, podemos usar el slicing para filas y columnas.

df.loc[0:2, 'nombre': 'email']

  nombre apellido                 email
0  Marta     Ruiz   martaruiz@gmail.com
1   Luis    Lopez   luislopez@gmail.com
2    Ana  Santana  anasantana@gmail.com

### <u>***UNIDAD 3: INDICES (set, reset, etc.)***</u>

In [ ]:
# Diccionario con listas de varias personas

gente={
    'nombre': ['Marta', 'Luis', 'Ana'],
    'apellido': ['Ruiz', 'Lopez', 'Santana'],
    'email': ['martaruiz@gmail.com', 'luislopez@gmail.com', 'anasantana@gmail.com']
}

In [ ]:
# Creamos el dataframe utilizando el diccionario del snippet anterior.

df=pd.DataFrame(gente)

df

  nombre apellido                 email
0  Marta     Ruiz   martaruiz@gmail.com
1   Luis    Lopez   luislopez@gmail.com
2    Ana  Santana  anasantana@gmail.com



---


Podemos cambiar los indices numéricos por defecto de los dataframe, usando el método de Pandas `set_index()`. Este método establece el índice del DataFrame (etiquetas de fila) utilizando una o más columnas o arrays existentes (de la longitud correcta).

> *El índice puede sustituir al índice existente o ampliarlo*.

En el siguiente snippet, vamos a cambiar los índices predeterminados (0, 1, 2, ...) por los valores de la columna "emails" que también son valores únicos en cada fila y, por tanto, para cada persona del DF. (Esto es similar a establecer una ***primary key*** en SQL).

El parámetro `inplace=True` acepta valores booleanos y se utiliza para indicar si se modifica el DataFrame en lugar de crear uno nuevo. Por defecto, el valor es `False`, y este ejemplo en concreto estamos creando un dataframe nuevo.

Mas info en [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html#pandas.DataFrame.set_index).

In [ ]:
df.set_index('email', inplace=True)

df

                     nombre apellido
email
martaruiz@gmail.com   Marta     Ruiz
luislopez@gmail.com    Luis    Lopez
anasantana@gmail.com    Ana  Santana

In [ ]:
df.index

Index(['martaruiz@gmail.com', 'luislopez@gmail.com', 'anasantana@gmail.com'], dtype='object', name='email')



---


Si queremos poner los nuevos indices por orden alfabetico usamos la funcion `sort_index()`.

Más info en [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_index.html).

In [ ]:
df.sort_index()

  nombre apellido                 email
0  Marta     Ruiz   martaruiz@gmail.com
1   Luis    Lopez   luislopez@gmail.com
2    Ana  Santana  anasantana@gmail.com

Para que el orden sea el contrario (descendente) al alfabetico usamos el
parámetro `ascending = False`

In [ ]:
df.sort_index(ascending=False)

  nombre apellido                 email
2    Ana  Santana  anasantana@gmail.com
1   Luis    Lopez   luislopez@gmail.com
0  Marta     Ruiz   martaruiz@gmail.com

In [ ]:
# Usamos la propiedad "index" para ver los índices del dataframe.

df.index

Index(['martaruiz@gmail.com', 'luislopez@gmail.com', 'anasantana@gmail.com'], dtype='object', name='email')



---


Después de los cambios realizados en el índice de las filas, donde antes usábamos el índice numérico (0, 1, 2, ...), ahora vamos a usar el valor string de la columna "email", junto con la propiedad `loc`.

In [ ]:
df.loc['anasantana@gmail.com']

nombre          Ana
apellido    Santana
Name: anasantana@gmail.com, dtype: object

In [ ]:
# También podemos detallar mas la consulta, añadiendo una columna:

df.loc['anasantana@gmail.com', 'apellido']

'Santana'



---


Como comentamos anteriormente, teniendo en cuenta los paradisgmas que usan las propiedades `loc` e `iloc` respectivamente, al no usar ya índices numéricos, no podemos usarlos en la propiedad `loc`, ya que ésta nos arrojaría un error.

In [ ]:
# La ejecución de este snippet causa un error.

df.loc[0]

KeyError: ignored

Sin embargo, con la propiedad `iloc` si podemos seguir usando los indices numericos anteriores.

In [ ]:
df.iloc[0]

nombre      Marta
apellido     Ruiz
Name: martaruiz@gmail.com, dtype: object



---


Si queremos volver a poner los indices por defecto, usamos la funcion `reset_index()`.

En el siguiente snippet volvemos a usar el parámetro `inplace=True`.

Más info en [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html).

In [ ]:
df.reset_index(inplace=True)

df

   index                 email nombre apellido
0      0   martaruiz@gmail.com  Marta     Ruiz
1      1   luislopez@gmail.com   Luis    Lopez
2      2  anasantana@gmail.com    Ana  Santana

### <u>***UNIDAD 4. FILTRAR DATAFRAME Y BUSCAR DATOS QUE CUMPLAN DETERMINADAS CONDICIONES (and Y or)***</u>

Comenzamos esta sección creando un dataframe a partir de un diccionario que vamos a definir, y mediante el constructor de Pandas `pd.Dataframe()`.

In [ ]:
gente={
    'nombre': ['Marta', 'Luis', 'Ana', 'Andres', 'Monica', 'Ana'],
    'apellido': ['Ruiz', 'Lopez', 'Santana', 'Lopez', 'Castro', 'Perez'],
    'email': ['martaruiz@gmail.com', 'luislopez@gmail.com', 'anasantana@gmail.com', 'andreslopez@gmail.com', 'monicacastro@gmail.com', 'saraperez@gmail.com'],
    'edad': [35, 28, 35, 'NaN', 53, 67],
    'salario': [20000, 25000, 50000, 17000, 20000, 65000],
    'ciudad' :['Madrid', 'Valencia', 'Malaga', 'Cadiz', 'Burgos', 'Madrid'],
    'casado': ['Yes', 'No', 'Yes', 'No', 'NaN', 'Yes']
}

#NaN =   not a number

In [ ]:
df=pd.DataFrame(gente)

df

   nombre apellido                   email edad  salario    ciudad casado
0   Marta     Ruiz     martaruiz@gmail.com   35    20000    Madrid    Yes
1    Luis    Lopez     luislopez@gmail.com   28    25000  Valencia     No
2     Ana  Santana    anasantana@gmail.com   35    50000    Malaga    Yes
3  Andres    Lopez   andreslopez@gmail.com  NaN    17000     Cadiz     No
4  Monica   Castro  monicacastro@gmail.com   53    20000    Burgos    NaN
5     Ana    Perez     saraperez@gmail.com   67    65000    Madrid    Yes

<u>*Filtro 1*</u>: ¿Quienes tienen el apellido López?

In [ ]:
# Al usar el operador de comparación "igual" (==), el resultado es un valor
# booleano para cada fila.

df['apellido'] == 'Lopez'

0    False
1     True
2    False
3     True
4    False
5    False
Name: apellido, dtype: bool

<u>*Filtro 2*</u>: Mostrar todos los registros que contengan el apellido "López".

In [ ]:
df[df['apellido']== 'Lopez']

   nombre apellido                  email edad  salario    ciudad casado
1    Luis    Lopez    luislopez@gmail.com   28    25000  Valencia     No
3  Andres    Lopez  andreslopez@gmail.com  NaN    17000     Cadiz     No

In [ ]:
#Ahora queremos solo informacion especifica del email de esas dos personas

df.loc[df['apellido'] == 'Lopez', 'email']

1      luislopez@gmail.com
3    andreslopez@gmail.com
Name: email, dtype: object

> En Pandas, el operador `and` se representa con el símbolo `&`, y el operador `or` se representa con el símbolo `|` (este símbolo se consigue pulsando las teclas: <mark>*alt gr* + 1</mark>).

<u>*Filtro 3*</u>: Mostrar los registros cuyo apellido sea López ***y*** cuyo nombre sea Andrés.

In [ ]:
filt= (df['apellido'] == 'Lopez') & (df['nombre'] == 'Andres')

df[filt]

   nombre apellido                  email edad  salario ciudad casado
3  Andres    Lopez  andreslopez@gmail.com  NaN    17000  Cadiz     No

In [ ]:
df[(df['apellido']== 'Lopez') & (df['nombre']== 'Andres')]

   nombre apellido                  email edad  salario ciudad casado
3  Andres    Lopez  andreslopez@gmail.com  NaN    17000  Cadiz     No

<u>*Filtro 4*</u>: Mostrar los registros cuyo apellido sea López ***o*** cuyo nombre sea Ana.

In [ ]:
df[(df['apellido'] == 'Lopez') | (df['nombre'] == 'Ana')]

   nombre apellido                  email edad  salario    ciudad casado
1    Luis    Lopez    luislopez@gmail.com   28    25000  Valencia     No
2     Ana  Santana   anasantana@gmail.com   35    50000    Malaga    Yes
3  Andres    Lopez  andreslopez@gmail.com  NaN    17000     Cadiz     No
5     Ana    Perez    saraperez@gmail.com   67    65000    Madrid    Yes

> La negación lógica (***not***) en Pandas se representa con el símbolo `~` (este símbolo se consigue pulsando las teclas: <mark>*alt gr* + 4</mark> y luego pulsando la tecla <mark>espacio</mark>.

<u>*Filtro 5*</u>: Mostrar los registros cuyo apellido <u>no</u> sea López ***o*** cuyo nombre <u>no</u> sea Ana.

In [ ]:
df[~(df['apellido'] == 'Lopez') & ~(df['nombre'] == 'Ana')]

   nombre apellido                   email edad  salario  ciudad casado
0   Marta     Ruiz     martaruiz@gmail.com   35    20000  Madrid    Yes
4  Monica   Castro  monicacastro@gmail.com   53    20000  Burgos    NaN

<u>*Filtro 6*</u>: Mostrar los registros de aquellas personas que ganen más de 35000€ de salario.

Esta vez, creamos una variable llamada `salario_alto` donde guardaremos el filtro (que ya sabemos que nos devuelve valores booleanos) y la usamos en el dataframe como notación de índices.

In [ ]:
df[df['salario'] > 35000]

  nombre apellido                 email edad  salario  ciudad casado
2    Ana  Santana  anasantana@gmail.com   35    50000  Malaga    Yes
5    Ana    Perez   saraperez@gmail.com   67    65000  Madrid    Yes

In [ ]:
df.loc[df['salario'] > 35000, ['edad', 'ciudad']]

  edad  ciudad
2   35  Malaga
5   67  Madrid

In [ ]:
df[df['salario'] > 35000][['edad', 'ciudad']]

  edad  ciudad
2   35  Malaga
5   67  Madrid

<u>*Filtro 7*</u>: Mostrar los registros de aquellas personas que vivan en Madrid y Málaga.

>El método `isin()` nos permite pasarle como parámetros un valor iterable (Series, Dataframe o diccionario) y nos devuelve un valor booleano de cada elemento del dataframe, indicando si está presente en el dataframe o columna(s) del dataframe en cuestión.

Más info del método `isin()` en [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isin.html).

In [ ]:
df[df['ciudad'].isin(['Madrid', 'Malaga'])]

  nombre apellido                 email edad  salario  ciudad casado
0  Marta     Ruiz   martaruiz@gmail.com   35    20000  Madrid    Yes
2    Ana  Santana  anasantana@gmail.com   35    50000  Malaga    Yes
5    Ana    Perez   saraperez@gmail.com   67    65000  Madrid    Yes

<u>*Filtro 8*</u>: Mostrar los registros de aquellas personas cuya ciudad contenga la letra "g".

>Para este filtro, usaremos el método `str.contains()` de las Series de Pandas, que nos permite comprobar si un patrón o regex (expresión regular, en íngles) está contenido en una cadena de una Serie o Índice .
>
>El parametro `case=False` es un valor booleano que:
+   Si es `True`, asume que el patrón es una expresión regular.
+   Si es `False`, trata el patrón como una cadena literal (string).

In [ ]:
df[df['ciudad'].str.contains('g', case=False)]

   nombre apellido                   email edad  salario  ciudad casado
2     Ana  Santana    anasantana@gmail.com   35    50000  Malaga    Yes
4  Monica   Castro  monicacastro@gmail.com   53    20000  Burgos    NaN

### <u>***UNIDAD 5. CAMBIAR DATOS EN EL DATAFRAME***</u>

In [ ]:
# Vamos a ver que columnas tiene nuestro DF

df.columns

Index(['nombre', 'apellido', 'email', 'edad', 'salario', 'ciudad', 'casado'], dtype='object')

Vamos a cambiar el nombre de todas las columnas al ingles

In [ ]:
df.columns=['name', 'last_name', 'email', 'age', 'salary', 'city', 'married']

df.columns

Index(['name', 'last_name', 'email', 'age', 'salary', 'city', 'married'], dtype='object')

In [ ]:
# Para ver todo el DF

df

     name last_name                   email  age  salary      city married
0   Marta      Ruiz     martaruiz@gmail.com   35   20000    Madrid     Yes
1    Luis     Lopez     luislopez@gmail.com   28   25000  Valencia      No
2     Ana   Santana    anasantana@gmail.com   35   50000    Malaga     Yes
3  Andres     Lopez   andreslopez@gmail.com  NaN   17000     Cadiz      No
4  Monica    Castro  monicacastro@gmail.com   53   20000    Burgos     NaN
5     Ana     Perez     saraperez@gmail.com   67   65000    Madrid     Yes

Si queremos que los nombres de las columnas esten en mayusculas, utilizaremos una compresión de lista para las columnas y usaremos el método `upper()` de los *Strings* el la variable temporal del bucle `for`.

In [ ]:
df.columns = [x.upper() for x in df.columns]

df

     NAME LAST_NAME                   EMAIL  AGE  SALARY      CITY MARRIED
0   Marta      Ruiz     martaruiz@gmail.com   35   20000    Madrid     Yes
1    Luis     Lopez     luislopez@gmail.com   28   25000  Valencia      No
2     Ana   Santana    anasantana@gmail.com   35   50000    Malaga     Yes
3  Andres     Lopez   andreslopez@gmail.com  NaN   17000     Cadiz      No
4  Monica    Castro  monicacastro@gmail.com   53   20000    Burgos     NaN
5     Ana     Perez     saraperez@gmail.com   67   65000    Madrid     Yes

Si quieres quitar espacios entre palabras y meter guiones bajos por ejemplo, o hacer lo contrario, usaremos el método `str.replace()` de los Strings en las columnas del dataframe.

In [ ]:
df.columns= df.columns.str.replace('_', ' ')

df

     NAME LAST NAME                   EMAIL  AGE  SALARY      CITY MARRIED
0   Marta      Ruiz     martaruiz@gmail.com   35   20000    Madrid     Yes
1    Luis     Lopez     luislopez@gmail.com   28   25000  Valencia      No
2     Ana   Santana    anasantana@gmail.com   35   50000    Malaga     Yes
3  Andres     Lopez   andreslopez@gmail.com  NaN   17000     Cadiz      No
4  Monica    Castro  monicacastro@gmail.com   53   20000    Burgos     NaN
5     Ana     Perez     saraperez@gmail.com   67   65000    Madrid     Yes

Vamos a dejar los nombres de las columnas en minusculas otra vez usando, esta vez, el método `lower()` de los Strings en la compresión de listas.

In [ ]:
df.columns = [x.lower() for x in df.columns]

df

     name last name                   email  age  salary      city married
0   Marta      Ruiz     martaruiz@gmail.com   35   20000    Madrid     Yes
1    Luis     Lopez     luislopez@gmail.com   28   25000  Valencia      No
2     Ana   Santana    anasantana@gmail.com   35   50000    Malaga     Yes
3  Andres     Lopez   andreslopez@gmail.com  NaN   17000     Cadiz      No
4  Monica    Castro  monicacastro@gmail.com   53   20000    Burgos     NaN
5     Ana     Perez     saraperez@gmail.com   67   65000    Madrid     Yes

Si solo queremos cambiar el nombre de algunas columnas, usamos el método `rename` de dataframes en Pandas y un diccionario.

Más info en [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html#pandas.DataFrame.rename).

In [ ]:
df.rename(columns={'name': 'nombre', 'last name': 'apellido', 'age':'edad', 'city': 'ciudad'}, inplace=True)

df

   nombre apellido                   email edad  salary    ciudad married
0   Marta     Ruiz     martaruiz@gmail.com   35   20000    Madrid     Yes
1    Luis    Lopez     luislopez@gmail.com   28   25000  Valencia      No
2     Ana  Santana    anasantana@gmail.com   35   50000    Malaga     Yes
3  Andres    Lopez   andreslopez@gmail.com  NaN   17000     Cadiz      No
4  Monica   Castro  monicacastro@gmail.com   53   20000    Burgos     NaN
5     Ana    Perez     saraperez@gmail.com   67   65000    Madrid     Yes

Si queremos cambiar un solo valor dentro del dataframe, por ejemplo, cambiar el apellido a Monica Castro, utilizaremos la propiedad `loc` indicando el índice de
fila y la columna a cambiar.

In [ ]:
df.loc[4, 'apellido'] = 'Romero'

df

   nombre apellido                   email edad  salary    ciudad married
0   Marta     Ruiz     martaruiz@gmail.com   35   20000    Madrid     Yes
1    Luis    Lopez     luislopez@gmail.com   28   25000  Valencia      No
2     Ana  Santana    anasantana@gmail.com   35   50000    Malaga     Yes
3  Andres    Lopez   andreslopez@gmail.com  NaN   17000     Cadiz      No
4  Monica   Romero  monicacastro@gmail.com   53   20000    Burgos     NaN
5     Ana    Perez     saraperez@gmail.com   67   65000    Madrid     Yes

En esta ocasión, vamos a cambiar la edad y el salario de Marta Ruiz.

In [ ]:
df.loc[0, ['edad', 'salary']] =[70, 78000]

df

   nombre apellido                   email edad  salary    ciudad married
0   Marta     Ruiz     martaruiz@gmail.com   70   78000    Madrid     Yes
1    Luis    Lopez     luislopez@gmail.com   28   25000  Valencia      No
2     Ana  Santana    anasantana@gmail.com   35   50000    Malaga     Yes
3  Andres    Lopez   andreslopez@gmail.com  NaN   17000     Cadiz      No
4  Monica   Romero  monicacastro@gmail.com   53   20000    Burgos     NaN
5     Ana    Perez     saraperez@gmail.com   67   65000    Madrid     Yes

Una propiedad parecida a `loc` es la funcion `at` pero ésta solo cambia un único dato.

En el siguiente snippet, vamos a darle a Marta Ruiz de nuevo su edad a 35 usando la propiedad `at`.

Más info en [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.at.html#pandas.DataFrame.at).

In [ ]:
df.at[0, 'edad'] = 35

df

   nombre apellido                   email edad  salary    ciudad married
0   Marta     Ruiz     martaruiz@gmail.com   35   78000    Madrid     Yes
1    Luis    Lopez     luislopez@gmail.com   28   25000  Valencia      No
2     Ana  Santana    anasantana@gmail.com   35   50000    Malaga     Yes
3  Andres    Lopez   andreslopez@gmail.com  NaN   17000     Cadiz      No
4  Monica   Romero  monicacastro@gmail.com   53   20000    Burgos     NaN
5     Ana    Perez     saraperez@gmail.com   67   65000    Madrid     Yes

Vamos a cambiar los nombres de columnas que quedaban en ingles al español (salary y married).

In [ ]:
df.rename(columns={'salary': 'salario', 'married': 'casado'}, inplace=True)

df

   nombre apellido                   email edad  salario    ciudad casado
0   Marta     Ruiz     martaruiz@gmail.com   35    78000    Madrid    Yes
1    Luis    Lopez     luislopez@gmail.com   28    25000  Valencia     No
2     Ana  Santana    anasantana@gmail.com   35    50000    Malaga    Yes
3  Andres    Lopez   andreslopez@gmail.com  NaN    17000     Cadiz     No
4  Monica   Romero  monicacastro@gmail.com   53    20000    Burgos    NaN
5     Ana    Perez     saraperez@gmail.com   67    65000    Madrid    Yes

Esta vez queremos cambiar la ciudad de la fila en la que el email es "saraperez@gmail.com".

In [ ]:
df.loc[df['email'] == 'saraperez@gmail.com', 'ciudad'] = 'Paris'
df

   nombre apellido                   email edad  salario    ciudad casado
0   Marta     Ruiz     martaruiz@gmail.com   35    20000    Madrid    Yes
1    Luis    Lopez     luislopez@gmail.com   28    25000  Valencia     No
2     Ana  Santana    anasantana@gmail.com   35    50000    Malaga    Yes
3  Andres    Lopez   andreslopez@gmail.com  NaN    17000     Cadiz     No
4  Monica   Castro  monicacastro@gmail.com   53    20000    Burgos    NaN
5     Ana    Perez     saraperez@gmail.com   67    65000     Paris    Yes

Si queremos actualizar multiples filas y convertirlas en mayúsculas, usaremos el método `str.upper()` de los Strings en la columna que queramos modificar.

In [ ]:
df['email'].str.upper()

0       MARTARUIZ@GMAIL.COM
1       LUISLOPEZ@GMAIL.COM
2      ANASANTANA@GMAIL.COM
3     ANDRESLOPEZ@GMAIL.COM
4    MONICACASTRO@GMAIL.COM
5       SARAPEREZ@GMAIL.COM
Name: email, dtype: object

Si ahora queremos ver todo el dataframe con los emails conertidos a mayúsculas, aplicaremos la sentencia del snippet anterior a la columna "email" de nuestro dataframe.

In [ ]:
df['email']= df['email'].str.upper()

df

   nombre apellido                   email edad  salario    ciudad casado
0   Marta     Ruiz     MARTARUIZ@GMAIL.COM   35    78000    Madrid    Yes
1    Luis    Lopez     LUISLOPEZ@GMAIL.COM   28    25000  Valencia     No
2     Ana  Santana    ANASANTANA@GMAIL.COM   35    50000    Malaga    Yes
3  Andres    Lopez   ANDRESLOPEZ@GMAIL.COM  NaN    17000     Cadiz     No
4  Monica   Romero  MONICACASTRO@GMAIL.COM   53    20000    Burgos    NaN
5     Ana    Perez     SARAPEREZ@GMAIL.COM   67    65000     Paris    Yes



---


Vamos a usar varios métodos muy utiles para cambiar datos de un dataframe como son:
+   `apply()`. Mas info en [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html).
+   `map()`. Mas info en [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.map.html).
+   `applymap()`. Mas info en [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.applymap.html). *Este método ya está obsoleto a partir de la versión 2.1.0 de Pandas, y en su lugar se usa `map()`*.
+   `replace()`. Mas info en [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.replace.html).

El método `apply()` aplica una función a lo largo de un eje (fila o columna) del dataFrame.

En esta ocasión aplica la función `len` (sin paréntesis) para que nos devuelva la longitud de los valores de la columna "*email*".

In [ ]:
df['email'].apply(len)

0    19
1    19
2    20
3    21
4    22
5    19
Name: email, dtype: int64

El método `apply()` también se puede usar con funciones propias creadas por nosotros.

In [ ]:
def actualiza_email(email):
  return email.lower()

df['email'].apply(actualiza_email)  # En esta sentencia solo visualizamos la aplicación de la función que hemos creado.

0       martaruiz@gmail.com
1       luislopez@gmail.com
2      anasantana@gmail.com
3     andreslopez@gmail.com
4    monicacastro@gmail.com
5       saraperez@gmail.com
Name: email, dtype: object

A continuación, aplicamos los cambios de la función creada anteriormente `actualiza_email()`, a nuestro dataframe.

In [ ]:
df['email'] = df['email'].apply(actualiza_email)

df

   nombre apellido                   email edad  salario    ciudad casado
0   Marta     Ruiz     martaruiz@gmail.com   35    78000    Madrid    Yes
1    Luis    Lopez     luislopez@gmail.com   28    25000  Valencia     No
2     Ana  Santana    anasantana@gmail.com   35    50000    Malaga    Yes
3  Andres    Lopez   andreslopez@gmail.com  NaN    17000     Cadiz     No
4  Monica   Romero  monicacastro@gmail.com   53    20000    Burgos    NaN
5     Ana    Perez     saraperez@gmail.com   67    65000     Paris    Yes



---



Si utilizamos el método `appy()` para Series (una sola columna)
no nos muestra lo que nosotros buscabamos que era la longitud (*len*) de todos los valores del dataframe. Solo nos muestra la cantidad de elementos que contiene cada columna, que son 6.


> Para Dataframes usamos el método `applymap()`.

In [ ]:
df.apply(len)

nombre      6
apellido    6
email       6
edad        6
salario     6
ciudad      6
casado      6
dtype: int64

Vamos a usar el método `applymap()` a continuación.

El siguiente snippet nos da error porque las columnas "*edad*" y "*salario*" tienen valores ***integer***. Más adelante tendremos que cambiar esos valores a *strings*.

In [ ]:
df.applymap(len)

TypeError: ignored

En esta ocasión, vamos a crear un nuevo dataframe pero con las columnas "*edad*" y "*salario*" de tipo *string*.

Nuevamente, creamos un diccionario con los nombres las columnas y los valores de cada columna en una lista.

Luego, como siempre, pasaremos ese diccionario a un dataframe.

In [ ]:
gentestr={
    'nombre': ['Marta', 'Luis', 'Ana', 'Andres', 'Monica', 'Ana'],
    'apellido': ['Ruiz', 'Lopez', 'Santana', 'Lopez', 'Castro', 'Perez'],
    'email': ['martaruiz@gmail.com', 'luislopez@gmail.com', 'anasantana@gmail.com', 'andreslopez@gmail.com', 'monicacastro@gmail.com', 'saraperez@gmail.com'],
    'edad': ['35', '28', '35', 'NaN', '53', '67'],
    'salario': ['20000', '25000', '50000', '17000', '20000', '65000'],
    'ciudad' :['Madrid', 'Valencia', 'Malaga', 'Cadiz', 'Burgos', 'Madrid'],
    'casado': ['Yes', 'No', 'Yes', 'No', 'NaN', 'Yes']
}

#NaN =   not a number

In [ ]:
df=pd.DataFrame(gentestr)

df

   nombre apellido                   email edad salario    ciudad casado
0   Marta     Ruiz     martaruiz@gmail.com   35   20000    Madrid    Yes
1    Luis    Lopez     luislopez@gmail.com   28   25000  Valencia     No
2     Ana  Santana    anasantana@gmail.com   35   50000    Malaga    Yes
3  Andres    Lopez   andreslopez@gmail.com  NaN   17000     Cadiz     No
4  Monica   Castro  monicacastro@gmail.com   53   20000    Burgos    NaN
5     Ana    Perez     saraperez@gmail.com   67   65000    Madrid    Yes

Ahora si podemos aplicar la funcion `len()` a todo el dataframe y nos da la longitud de todos los valores de cada columna del dataframe.

In [ ]:
df.applymap(len)

   nombre  apellido  email  edad  salario  ciudad  casado
0       5         4     19     2        5       6       3
1       4         5     19     2        5       8       2
2       3         7     20     2        5       6       3
3       6         5     21     3        5       5       2
4       6         6     22     2        5       6       3
5       3         5     19     2        5       6       3

Si queremos que todos los valores del dataframe pasen a mayúsculas, aplicamos el método `str.upper()` pasándolo como parámetro de nuestro método para dataframes `applymap()`.

In [ ]:
df.applymap(str.upper)

   nombre apellido                   email edad salario    ciudad casado
0   MARTA     RUIZ     MARTARUIZ@GMAIL.COM   35   20000    MADRID    YES
1    LUIS    LOPEZ     LUISLOPEZ@GMAIL.COM   28   25000  VALENCIA     NO
2     ANA  SANTANA    ANASANTANA@GMAIL.COM   35   50000    MALAGA    YES
3  ANDRES    LOPEZ   ANDRESLOPEZ@GMAIL.COM  NAN   17000     CADIZ     NO
4  MONICA   CASTRO  MONICACASTRO@GMAIL.COM   53   20000    BURGOS    NAN
5     ANA    PEREZ     SARAPEREZ@GMAIL.COM   67   65000    MADRID    YES

Volvemos a dejar los valores en minúsculas.

In [ ]:
df.applymap(str.lower)

   nombre apellido                   email edad salario    ciudad casado
0   marta     ruiz     martaruiz@gmail.com   35   20000    madrid    yes
1    luis    lopez     luislopez@gmail.com   28   25000  valencia     no
2     ana  santana    anasantana@gmail.com   35   50000    malaga    yes
3  andres    lopez   andreslopez@gmail.com  nan   17000     cadiz     no
4  monica   castro  monicacastro@gmail.com   53   20000    burgos    nan
5     ana    perez     saraperez@gmail.com   67   65000    madrid    yes



---

Como dijimos anteriormente, el método `map()` sustituye al método `applymap()`, quedando este último obsoleto a partir de la versión 2.1.0 de Pandas.

En el siguiente snippet, queremos cambiar dos valores de la columna "*nombre*".

<mark>* *Los nombres que no se han cambiado muestra NaN (Not A Number)*</mark>

In [ ]:
df['nombre'].map({'Marta':'Sofia','Andres':'Sandalio'})

0       Sofia
1         NaN
2         NaN
3    Sandalio
4         NaN
5         NaN
Name: nombre, dtype: object

También podemos usar el método de Pandas `replace()`.

In [ ]:
df['apellido'].replace({'Lopez': 'Santos', 'Perez': 'Salmeron'})

0        Ruiz
1      Santos
2     Santana
3      Santos
4      Castro
5    Salmeron
Name: apellido, dtype: object

Si vemos como queda el dataframe original vemos que los cambios realizados en las columnas "*nombre*" y "*apellido*" con ambos métodos solo eran temporales.

In [ ]:
df

   nombre apellido                   email edad salario    ciudad casado
0   Marta     Ruiz     martaruiz@gmail.com   35   20000    Madrid    Yes
1    Luis    Lopez     luislopez@gmail.com   28   25000  Valencia     No
2     Ana  Santana    anasantana@gmail.com   35   50000    Malaga    Yes
3  Andres    Lopez   andreslopez@gmail.com  NaN   17000     Cadiz     No
4  Monica   Castro  monicacastro@gmail.com   53   20000    Burgos    NaN
5     Ana    Perez     saraperez@gmail.com   67   65000    Madrid    Yes

Por tanto, tal y como hemos hecho en snippets anteriores, si queremos que los cambios queden fijos en el dataframe original entonces haremos lo siguiente, en este caso para la columna "*apellido*" y usando el método `replace()`.

In [ ]:
df['apellido'] =df['apellido'].replace({'Lopez': 'Santos', 'Perez': 'Salmeron'})

df

   nombre  apellido                   email edad salario    ciudad casado
0   Marta      Ruiz     martaruiz@gmail.com   35   20000    Madrid    Yes
1    Luis    Santos     luislopez@gmail.com   28   25000  Valencia     No
2     Ana   Santana    anasantana@gmail.com   35   50000    Malaga    Yes
3  Andres    Santos   andreslopez@gmail.com  NaN   17000     Cadiz     No
4  Monica    Castro  monicacastro@gmail.com   53   20000    Burgos    NaN
5     Ana  Salmeron     saraperez@gmail.com   67   65000    Madrid    Yes

### <u>***UNIDAD 6. AÑADIR Y QUITAR FILAS Y COLUMNAS DEL DATAFRAME. - COMBINAR INFORMACION***</u>

Podemos añadir una columna con la siguiente sintaxis:

1. Primero vemos como añadir una nueva columna a la DataFrame.

In [ ]:
# para añadir una nueva columna al DF
df['numero hijos']=[1, 2, 4, 2, 0, 1]
df

,nombre,apellido,email,edad,salario,ciudad,casado,numero hijos
0,Marta,Ruiz,martaruiz@gmail.com,35,20000,Madrid,Yes,1
1,Luis,Santos,luislopez@gmail.com,28,25000,Valencia,No,2
2,Ana,Santana,anasantana@gmail.com,35,50000,Malaga,Yes,4
3,Andres,Santos,andreslopez@gmail.com,NaN,17000,Cadiz,No,2
4,Monica,Castro,monicacastro@gmail.com,53,20000,Burgos,NaN,0
5,Ana,Salmeron,saraperez@gmail.com,67,65000,Madrid,Yes,1

In [ ]:
# cambiar la nueva columna a otra posicion de la dataframe

In [ ]:
columnas=list(df.columns)

In [ ]:
columnas.remove('numero hijos')

In [ ]:
posicion_deseada= 3
columnas.insert(posicion_deseada, 'numero hijos')

In [ ]:
df=df[columnas]

df

,nombre,apellido,email,numero hijos,edad,salario,ciudad,casado
0,Marta,Ruiz,martaruiz@gmail.com,1,35,20000,Madrid,Yes
1,Luis,Santos,luislopez@gmail.com,2,28,25000,Valencia,No
2,Ana,Santana,anasantana@gmail.com,4,35,50000,Malaga,Yes
3,Andres,Santos,andreslopez@gmail.com,2,NaN,17000,Cadiz,No
4,Monica,Castro,monicacastro@gmail.com,0,53,20000,Burgos,NaN
5,Ana,Salmeron,saraperez@gmail.com,1,67,65000,Madrid,Yes

In [ ]:
#para concatenar columnas usamos

df['nombre'] + ' ' + df['apellido']

0       Marta Ruiz
1      Luis Santos
2      Ana Santana
3    Andres Santos
4    Monica Castro
5     Ana Salmeron
dtype: object

2. Luego, en este caso, queremos crear una nueva columna "*nombre_apellido*", que contenga los valores de las columnas "*nombre*" y "*apellido*" separados por un espacio.

In [ ]:
df['nombre_apellido'] = df['nombre']+ ' ' +df['apellido']

df

,nombre,apellido,email,edad,salario,ciudad,casado,nombre_apellido
0,Marta,Ruiz,martaruiz@gmail.com,35,20000,Madrid,Yes,Marta Ruiz
1,Luis,Santos,luislopez@gmail.com,28,25000,Valencia,No,Luis Santos
2,Ana,Santana,anasantana@gmail.com,35,50000,Malaga,Yes,Ana Santana
3,Andres,Santos,andreslopez@gmail.com,NaN,17000,Cadiz,No,Andres Santos
4,Monica,Castro,monicacastro@gmail.com,53,20000,Burgos,NaN,Monica Castro
5,Ana,Salmeron,saraperez@gmail.com,67,65000,Madrid,Yes,Ana Salmeron



---


Ahora vamos a quitar columnas utilizando el método `drop()` de Pandas.

Más info en [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html).

In [ ]:
df.drop(columns= ['nombre', 'apellido'])

KeyError: ignored

In [ ]:
# Como en casos anteriores, vemos que no ha hecho el cambio permanente.

df

,nombre,apellido,email,edad,salario,ciudad,casado,nombre_apellido
0,Marta,Ruiz,martaruiz@gmail.com,35,20000,Madrid,Yes,Marta Ruiz
1,Luis,Santos,luislopez@gmail.com,28,25000,Valencia,No,Luis Santos
2,Ana,Santana,anasantana@gmail.com,35,50000,Malaga,Yes,Ana Santana
3,Andres,Santos,andreslopez@gmail.com,NaN,17000,Cadiz,No,Andres Santos
4,Monica,Castro,monicacastro@gmail.com,53,20000,Burgos,NaN,Monica Castro
5,Ana,Salmeron,saraperez@gmail.com,67,65000,Madrid,Yes,Ana Salmeron

Procedemos a realizar el cambio permanente, que se consigue con el parámetro `inplace=True`

In [ ]:
df.drop(columns= ['nombre', 'apellido'], inplace=True)

df

                    email edad salario    ciudad casado nombre_apellido
0     martaruiz@gmail.com   35   20000    Madrid    Yes      Marta Ruiz
1     luislopez@gmail.com   28   25000  Valencia     No     Luis Santos
2    anasantana@gmail.com   35   50000    Malaga    Yes     Ana Santana
3   andreslopez@gmail.com  NaN   17000     Cadiz     No   Andres Santos
4  monicacastro@gmail.com   53   20000    Burgos    NaN   Monica Castro
5     saraperez@gmail.com   67   65000    Madrid    Yes    Ana Salmeron

Para revertir lo hecho y convertir la columna "*nombre_apellido*" en dos columnas una para "*nombre*" y otra para "*apellido*", necesitamos utilizar el método `str.split()` de Series de Pandas.

Más info en [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.split.html#pandas.Series.str.split).

1. Primero vemos cómo funciona el método `str.split()`.

In [ ]:
df['nombre_apellido'].str.split(' ')

0       [Marta, Ruiz]
1      [Luis, Santos]
2      [Ana, Santana]
3    [Andres, Santos]
4    [Monica, Castro]
5     [Ana, Salmeron]
Name: nombre_apellido, dtype: object

2. Ahora, para que pongamos estos datos en dos columnas necesitamos usar el parámetro `expand=True`.

>> Este parámetro expande las cadenas divididas en columnas separadas, de tal forma que:
+   Si es `True`, devuelve DataFrame / MultiIndice expandiendo la dimensionalidad (creando una columna para cada string resultante de la división (split).
+   Si es `False`, devuelve Series/Index, que contiene listas de cadenas.

In [ ]:
df['nombre_apellido'].str.split(' ', expand=True)

        0         1
0   Marta      Ruiz
1    Luis    Santos
2     Ana   Santana
3  Andres    Santos
4  Monica    Castro
5     Ana  Salmeron

Evidentemente, ahora toca realizar esta acción en el dataframe, creando las dos nuevas columnas "*nombre*" y "*apellido*" y asignandoles como valores el resultado de divivir el valor de la columna "*nombre_apellido*", tal y como hemos hecho en la sentencia del snippet anterior.

In [ ]:
df[['nombre', 'apellido']] = df['nombre_apellido'].str.split(' ', expand=True)

In [ ]:
# Visualizamos los cambios realizados.

df

,email,edad,salario,ciudad,casado,nombre_apellido,nombre,apellido
0,martaruiz@gmail.com,35,20000,Madrid,Yes,Marta Ruiz,Marta,Ruiz
1,luislopez@gmail.com,28,25000,Valencia,No,Luis Santos,Luis,Santos
2,anasantana@gmail.com,35,50000,Malaga,Yes,Ana Santana,Ana,Santana
3,andreslopez@gmail.com,NaN,17000,Cadiz,No,Andres Santos,Andres,Santos
4,monicacastro@gmail.com,53,20000,Burgos,NaN,Monica Castro,Monica,Castro
5,saraperez@gmail.com,67,65000,Madrid,Yes,Ana Salmeron,Ana,Salmeron



---


Podemos añadir una fila a un dataframe, sin importar si queremos rellenar todos los valores de todas las columnas o solo una parte de ellas.

En el siguiente snippet, vamos a añadir una nueva persona y solo vamos a añadir el campo "*nombre*". El resto de columnas se rellenarán como ***NaN***.

In [ ]:
fila = {'nombre':'Peter'}

df.loc[len(df)] = fila

# Puedes añadir al diccionario los otros valores para llenar todas las celdas
# con informacion sobre Peter si quieres hacer pruebas.

In [ ]:
df

,email,edad,salario,ciudad,casado,nombre_apellido,nombre,apellido
0,martaruiz@gmail.com,35,20000,Madrid,Yes,Marta Ruiz,Marta,Ruiz
1,luislopez@gmail.com,28,25000,Valencia,No,Luis Santos,Luis,Santos
2,anasantana@gmail.com,35,50000,Malaga,Yes,Ana Santana,Ana,Santana
3,andreslopez@gmail.com,NaN,17000,Cadiz,No,Andres Santos,Andres,Santos
4,monicacastro@gmail.com,53,20000,Burgos,NaN,Monica Castro,Monica,Castro
5,saraperez@gmail.com,67,65000,Madrid,Yes,Ana Salmeron,Ana,Salmeron
6,NaN,NaN,NaN,NaN,NaN,NaN,Peter,NaN

In [ ]:
# Para quitar filas usamos los indices

df = df.drop(index=6)

,email,edad,salario,ciudad,casado,nombre_apellido,nombre,apellido
0,martaruiz@gmail.com,35,20000,Madrid,Yes,Marta Ruiz,Marta,Ruiz
1,luislopez@gmail.com,28,25000,Valencia,No,Luis Santos,Luis,Santos
2,anasantana@gmail.com,35,50000,Malaga,Yes,Ana Santana,Ana,Santana
3,andreslopez@gmail.com,NaN,17000,Cadiz,No,Andres Santos,Andres,Santos
4,monicacastro@gmail.com,53,20000,Burgos,NaN,Monica Castro,Monica,Castro
5,saraperez@gmail.com,67,65000,Madrid,Yes,Ana Salmeron,Ana,Salmeron

In [ ]:
# Para eliminar mas filas de golpe enumeramos los índices a eliminar.

df = df.drop(index=[3,4,5])

df

,email,edad,salario,ciudad,casado,nombre_apellido,nombre,apellido
0,martaruiz@gmail.com,35,20000,Madrid,Yes,Marta Ruiz,Marta,Ruiz
1,luislopez@gmail.com,28,25000,Valencia,No,Luis Santos,Luis,Santos
2,anasantana@gmail.com,35,50000,Malaga,Yes,Ana Santana,Ana,Santana

In [ ]:
# Para eliminar mas filas usando el slicing o rango de indices

df=df.drop(df.index[1:3])

df

,email,edad,salario,ciudad,casado,nombre_apellido,nombre,apellido
0,martaruiz@gmail.com,35,20000,Madrid,Yes,Marta Ruiz,Marta,Ruiz

# UNIDAD 7. CLASIFICAR DATOS

In [ ]:
import pandas as pd
gente={
    'nombre': ['Marta', 'Luis', 'Ana', 'Andres', 'Monica', 'Ana'],
    'apellido': ['Ruiz', 'Lopez', 'Santana', 'Lopez', 'Castro', 'Perez'],
    'email': ['martaruiz@gmail.com', 'luislopez@gmail.com', 'anasantana@gmail.com', 'andreslopez@gmail.com', 'monicacastro@gmail.com', 'saraperez@gmail.com'],
    'edad': [35, 28, 35, 'NaN', 53, 67],
    'salario': [20000, 25000, 50000, 17000, 20000, 65000],
    'ciudad' :['Madrid', 'Valencia', 'Malaga', 'Cadiz', 'Burgos', 'Madrid'],
    'casado': ['Yes', 'No', 'Yes', 'No', 'NaN', 'Yes']
}

In [ ]:
df=pd.DataFrame(gente)

df

   nombre apellido                   email edad  salario    ciudad casado
0   Marta     Ruiz     martaruiz@gmail.com   35    20000    Madrid    Yes
1    Luis    Lopez     luislopez@gmail.com   28    25000  Valencia     No
2     Ana  Santana    anasantana@gmail.com   35    50000    Malaga    Yes
3  Andres    Lopez   andreslopez@gmail.com  NaN    17000     Cadiz     No
4  Monica   Castro  monicacastro@gmail.com   53    20000    Burgos    NaN
5     Ana    Perez     saraperez@gmail.com   67    65000    Madrid    Yes

In [ ]:
#vamos a ordenar

df.sort_values(by='nombre')

   nombre apellido                   email edad  salario    ciudad casado
2     Ana  Santana    anasantana@gmail.com   35    50000    Malaga    Yes
5     Ana    Perez     saraperez@gmail.com   67    65000    Madrid    Yes
3  Andres    Lopez   andreslopez@gmail.com  NaN    17000     Cadiz     No
1    Luis    Lopez     luislopez@gmail.com   28    25000  Valencia     No
0   Marta     Ruiz     martaruiz@gmail.com   35    20000    Madrid    Yes
4  Monica   Castro  monicacastro@gmail.com   53    20000    Burgos    NaN

In [ ]:
#si queremos que esta vez sea en orden descendente

df.sort_values(by='nombre', ascending=False)

   nombre apellido                   email edad  salario    ciudad casado
4  Monica   Castro  monicacastro@gmail.com   53    20000    Burgos    NaN
0   Marta     Ruiz     martaruiz@gmail.com   35    20000    Madrid    Yes
1    Luis    Lopez     luislopez@gmail.com   28    25000  Valencia     No
3  Andres    Lopez   andreslopez@gmail.com  NaN    17000     Cadiz     No
2     Ana  Santana    anasantana@gmail.com   35    50000    Malaga    Yes
5     Ana    Perez     saraperez@gmail.com   67    65000    Madrid    Yes

In [ ]:
#para ordenar los apellidos en orden ascendente y los nombres tambien hacemos
#esto y vemos que los nombres Andres y Luis, de los dos apellidos Lopez tambien estan en orden
#ascendente
df.sort_values(by=['apellido', 'nombre'])

   nombre apellido                   email edad  salario    ciudad casado
4  Monica   Castro  monicacastro@gmail.com   53    20000    Burgos    NaN
3  Andres    Lopez   andreslopez@gmail.com  NaN    17000     Cadiz     No
1    Luis    Lopez     luislopez@gmail.com   28    25000  Valencia     No
5     Ana    Perez     saraperez@gmail.com   67    65000    Madrid    Yes
0   Marta     Ruiz     martaruiz@gmail.com   35    20000    Madrid    Yes
2     Ana  Santana    anasantana@gmail.com   35    50000    Malaga    Yes

In [ ]:
#si ahora queremos que los apellidos esten en orden descendente y los nombres
#en orden ascendente usamos booleanos
df.sort_values(by=['apellido', 'nombre'], ascending=[False, True])

   nombre apellido                   email edad  salario    ciudad casado
2     Ana  Santana    anasantana@gmail.com   35    50000    Malaga    Yes
0   Marta     Ruiz     martaruiz@gmail.com   35    20000    Madrid    Yes
5     Ana    Perez     saraperez@gmail.com   67    65000    Madrid    Yes
3  Andres    Lopez   andreslopez@gmail.com  NaN    17000     Cadiz     No
1    Luis    Lopez     luislopez@gmail.com   28    25000  Valencia     No
4  Monica   Castro  monicacastro@gmail.com   53    20000    Burgos    NaN

In [ ]:
#de nuevo si queremos dejar fijos estos cambios añadiremos el inplace=True
#al final del parentesis y despues de una coma
#df.sort_values(by=['apellido', 'nombre'], ascending=[False, True], inplace=True)

In [ ]:
#si queremos tener los indices ordenados otra vez 0, 1, 2, 3, etc,
#escribimos

df.sort_index()

   nombre apellido                   email edad  salario    ciudad casado
0   Marta     Ruiz     martaruiz@gmail.com   35    20000    Madrid    Yes
1    Luis    Lopez     luislopez@gmail.com   28    25000  Valencia     No
2     Ana  Santana    anasantana@gmail.com   35    50000    Malaga    Yes
3  Andres    Lopez   andreslopez@gmail.com  NaN    17000     Cadiz     No
4  Monica   Castro  monicacastro@gmail.com   53    20000    Burgos    NaN
5     Ana    Perez     saraperez@gmail.com   67    65000    Madrid    Yes

In [ ]:
#si queremos ordenar los datos de una sola columna por ejemplo apellido

df['apellido'].sort_values()

4     Castro
1      Lopez
3      Lopez
5      Perez
0       Ruiz
2    Santana
Name: apellido, dtype: object

In [ ]:
#si queremos ver solo los 3 salarios mas altos usamos otra
#funcion nlargest()

df['salario'].nlargest(3)

5    65000
2    50000
1    25000
Name: salario, dtype: int64

In [ ]:
#para que nos muestre toda la informacion de esas personas con los 3
#salarios mas altos haremos

df.nlargest(3, 'salario')

  nombre apellido                 email edad  salario    ciudad casado
5    Ana    Perez   saraperez@gmail.com   67    65000    Madrid    Yes
2    Ana  Santana  anasantana@gmail.com   35    50000    Malaga    Yes
1   Luis    Lopez   luislopez@gmail.com   28    25000  Valencia     No

In [ ]:
#si queremos hacer lo contrario

df.nsmallest(2, 'salario')

   nombre apellido                  email edad  salario  ciudad casado
3  Andres    Lopez  andreslopez@gmail.com  NaN    17000   Cadiz     No
0   Marta     Ruiz    martaruiz@gmail.com   35    20000  Madrid    Yes

# UNIDAD 8. AGREGAR Y AGRUPAR DATOS

In [ ]:
import pandas as pd


gentestr={
    'nombre': ['Marta', 'Luis', 'Ana', 'Andres', 'Monica', 'Ana', 'Rocio', 'Pepe'],
    'apellido': ['Ruiz', 'Lopez', 'Santana', 'Lopez', 'Castro', 'Perez', 'Iglesias', 'Fuentes'],
    'email': ['martaruiz@gmail.com', 'luislopez@gmail.com', 'anasantana@gmail.com', 'andreslopez@gmail.com',
    'monicacastro@gmail.com', 'saraperez@gmail.com', 'rocioiglesias@gmail.com', 'pepefuentes@gmail.com'],
    'edad': [35, 28, 35, 49, 53, 67, 73, 19],
    'salario': ['20000', '25000', '50000', '17000', '20000', '65000', '83000', '97000'],
    'ciudad' :['Madrid', 'Valencia', 'Malaga', 'Cadiz', 'Burgos', 'Madrid', 'Madrid', 'Madrid'],
    'casado': ['Yes', 'No', 'Yes', 'No', 'NaN', 'Yes', 'Yes', 'No']
}

In [ ]:
df=pd.DataFrame(gentestr)

df

   nombre  apellido                    email  edad salario    ciudad casado
0   Marta      Ruiz      martaruiz@gmail.com    35   20000    Madrid    Yes
1    Luis     Lopez      luislopez@gmail.com    28   25000  Valencia     No
2     Ana   Santana     anasantana@gmail.com    35   50000    Malaga    Yes
3  Andres     Lopez    andreslopez@gmail.com    49   17000     Cadiz     No
4  Monica    Castro   monicacastro@gmail.com    53   20000    Burgos    NaN
5     Ana     Perez      saraperez@gmail.com    67   65000    Madrid    Yes
6   Rocio  Iglesias  rocioiglesias@gmail.com    73   83000    Madrid    Yes
7    Pepe   Fuentes    pepefuentes@gmail.com    19   97000    Madrid     No

In [ ]:
#empezamos con funciones de agregacion, empezamos con la mediana de salarios
df['salario'].median()

37500.0

In [ ]:
#la moda o numero mas repetido de la lista
df['salario'].mode()

0    20000
Name: salario, dtype: object

In [ ]:
#tambien podemos ver la mediana de todo el DF
df.median()

<ipython-input-62-e1ad2147fe65>:2: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.median()

edad          42.0
salario    37500.0
dtype: float64

In [ ]:
df.describe()

            edad
count   8.000000
mean   44.875000
std    18.946824
min    19.000000
25%    33.250000
50%    42.000000
75%    56.500000
max    73.000000

In [ ]:
#la funcion count() nos da el numero de personas que contestan
df['casado'].count()

8

In [ ]:
#para saber cuantos contestaron Yes y cuantos No usamos otra funcion
df['casado'].value_counts()

Yes    4
No     3
NaN    1
Name: casado, dtype: int64

In [ ]:
#si queremos ver cual es la ciudad mas comun en nuestro DF
df['ciudad'].value_counts()

Madrid      4
Valencia    1
Malaga      1
Cadiz       1
Burgos      1
Name: ciudad, dtype: int64

In [ ]:
#si queremos ver los resultados anteriores pero en porcentajes usamos
#la funcion normalize
df['ciudad'].value_counts(normalize=True)

Madrid      0.500
Valencia    0.125
Malaga      0.125
Cadiz       0.125
Burgos      0.125
Name: ciudad, dtype: float64

In [ ]:
#vamos a ver otras funciones de agregacion como groupby() y get_group()

df.groupby(['ciudad'])

In [ ]:
ciudad_grupo=df.groupby(['ciudad'])

In [ ]:
#queremos que nos agregue toda la informacion que tiene la ciudad Madrid
ciudad_grupo.get_group('Madrid')

  nombre  apellido                    email  edad salario  ciudad casado
0  Marta      Ruiz      martaruiz@gmail.com    35   20000  Madrid    Yes
5    Ana     Perez      saraperez@gmail.com    67   65000  Madrid    Yes
6  Rocio  Iglesias  rocioiglesias@gmail.com    73   83000  Madrid    Yes
7   Pepe   Fuentes    pepefuentes@gmail.com    19   97000  Madrid     No

In [ ]:
df.groupby('ciudad').get_group('Madrid')

  nombre  apellido                    email  edad salario  ciudad casado
0  Marta      Ruiz      martaruiz@gmail.com    35   20000  Madrid    Yes
5    Ana     Perez      saraperez@gmail.com    67   65000  Madrid    Yes
6  Rocio  Iglesias  rocioiglesias@gmail.com    73   83000  Madrid    Yes
7   Pepe   Fuentes    pepefuentes@gmail.com    19   97000  Madrid     No

In [ ]:
#si del grupo anterior solo nos interesa ahora saber los salarios que
#algunas personas ganan en Madrid usaremos

filt = df['ciudad'] == 'Madrid'
df.loc[filt]['salario'].value_counts()

20000    1
65000    1
83000    1
97000    1
Name: salario, dtype: int64

In [ ]:
# Filtramos el DataFrame para obtener solo las filas donde la ciudad es Madrid
madrid_info = df.groupby('ciudad').get_group('Madrid')

# Seleccionamos la columna 'salario' del DataFrame filtrado
salarios_madrid = madrid_info['salario']

print(salarios_madrid)

0    20000
5    65000
6    83000
7    97000
Name: salario, dtype: object

In [ ]:
#queremos saber cuantas personas de Madrid tienen la letra Y en la respuesta
#sobre si estan casados o no. usamos funcion contains() y la funcion sum()
filt=df['ciudad']== 'Madrid'
df.loc[filt]['casado'].str.contains('Y').sum()

3

In [ ]:
# Filtramos el DataFrame para obtener solo las filas donde la ciudad es Madrid
madrid_info = df.groupby('ciudad').get_group('Madrid')

# Contamos cuántas personas de Madrid tienen la letra 'Y' en la respuesta sobre si están casadas
personas_casadas_con_y = madrid_info['casado'].str.contains('Y').sum()

print("Cantidad de personas de Madrid con 'Y' en la respuesta sobre estar casados:", personas_casadas_con_y)

Cantidad de personas de Madrid con 'Y' en la respuesta sobre estar casados: 3

In [ ]:
#si queremos ver cuantas personas tienen la letra 'o' en su respuesta
filt=df['ciudad']== 'Madrid'
df.loc[filt]['casado'].str.contains('o').sum()

1

In [ ]:
# Filtrar el DataFrame para obtener solo las filas donde la ciudad es Madrid
madrid_info = df.groupby('ciudad').get_group('Madrid')

# Contar cuántas personas tienen la letra 'o' en su respuesta sobre estar casadas
personas_casadas_con_o = madrid_info['casado'].str.count('o').sum()

print("Cantidad de personas de Madrid con 'o' en la respuesta sobre estar casados:", personas_casadas_con_o)

Cantidad de personas de Madrid con 'o' en la respuesta sobre estar casados: 1

In [ ]:
#si queremos ver cuantas personas en la ciudad de Madrid tienen la letra 'u' en
#su apellido
filt=df['ciudad']== 'Madrid'
df.loc[filt]['apellido'].str.contains('u').sum()

2

In [ ]:
# Filtrar el DataFrame para obtener solo las filas donde la ciudad es Madrid
madrid_info = df[df['ciudad'] == 'Madrid']

# Contar cuántas personas tienen la letra 'u' en su apellido
personas_con_u_en_apellido = madrid_info['apellido'].str.count('u').sum()

print("Cantidad de personas en la ciudad de Madrid con 'u' en su apellido:", personas_con_u_en_apellido)

Cantidad de personas en la ciudad de Madrid con 'u' en su apellido: 2

In [ ]:
#muestra en pantalla los nombres de las personas de Madrid cuyos apellidos
#contienen una letra 'i'
filt = (df['ciudad'] == 'Madrid') & df['apellido'].str.contains('I', case=False)
nombre_filtro = df.loc[filt, 'nombre']
nombre_filtro

0    Marta
6    Rocio
Name: nombre, dtype: object

In [ ]:
# Filtrar el DataFrame para obtener solo las filas donde la ciudad es Madrid
madrid_info = df[df['ciudad'] == 'Madrid']

# Filtrar las filas donde el apellido contiene la letra 'i'
apellidos_con_i = madrid_info[madrid_info['apellido'].str.contains('i')]

# Imprimir los nombres de las personas con apellidos que contienen 'i'
print("Nombres de las personas de Madrid cuyos apellidos contienen la letra 'i':")
print(apellidos_con_i['nombre'])

Nombres de las personas de Madrid cuyos apellidos contienen la letra 'i':
0    Marta
6    Rocio
Name: nombre, dtype: object

In [ ]:
#muestra en pantalla los nombres de las personas de Madrid cuyos apellidos
#contienen una letra 'i' y tambien tienen mas de 50 años
filt = (df['ciudad'] == 'Madrid') & (df['edad']>50) & df['apellido'].str.contains('I', case=False)
nombre_filtro = df.loc[filt, 'nombre']
nombre_filtro

6    Rocio
Name: nombre, dtype: object

In [ ]:
# Filtrar el DataFrame para obtener solo las filas donde la ciudad es Madrid
madrid_info = df[df['ciudad'] == 'Madrid']

# Filtrar las filas donde el apellido contiene la letra 'i' y la edad es mayor a 50
personas_filtradas = madrid_info[madrid_info['apellido'].str.contains('i') & (madrid_info['edad'] > 50)]

# Imprimir los nombres de las personas que cumplen con las condiciones
print("Nombres de las personas de Madrid cuyos apellidos contienen la letra 'i' y tienen más de 50 años:")
print(personas_filtradas['nombre'])

Nombres de las personas de Madrid cuyos apellidos contienen la letra 'i' y tienen más de 50 años:
6    Rocio
Name: nombre, dtype: object

# UNIDAD 9. LIMPIEZA DE DATOS

In [ ]:
import pandas as pd

In [ ]:
gentelimp={
    'nombre': ['Marta', 'Luis', 'Ana', 'Andres', None, 'Ana'],
    'apellido': ['Ruiz', 'Lopez', 'Santana', None, 'Castro', 'Perez'],
    'email': ['martaruiz@gmail.com', 'luislopez@gmail.com', 'anasantana@gmail.com', 'andreslopez@gmail.com', None, 'saraperez@gmail.com'],
    'edad': [35, 28, 35, 49, 53, 67],
    'salario': [20000, 25000, None, 17000, 20000, 65000],
    'ciudad' :['Madrid', 'Valencia', 'Malaga', 'Cadiz', 'Burgos', None],
    'casado': ['Yes', 'No', 'Yes', 'No', None, None]
}

In [ ]:
df=pd.DataFrame(gentelimp)

df

   nombre apellido                  email  edad  salario    ciudad casado
0   Marta     Ruiz    martaruiz@gmail.com    35  20000.0    Madrid    Yes
1    Luis    Lopez    luislopez@gmail.com    28  25000.0  Valencia     No
2     Ana  Santana   anasantana@gmail.com    35      NaN    Malaga    Yes
3  Andres     None  andreslopez@gmail.com    49  17000.0     Cadiz     No
4    None   Castro                   None    53  20000.0    Burgos   None
5     Ana    Perez    saraperez@gmail.com    67  65000.0      None   None

In [ ]:
#algunas veces los mejor es eliminar las filas que contienen
#datos sucios o faltantes. vamos a usar la funcion dropna()
#drop (suprimir) na (not available o no disponible)

df.dropna()

  nombre apellido                email  edad  salario    ciudad casado
0  Marta     Ruiz  martaruiz@gmail.com    35  20000.0    Madrid    Yes
1   Luis    Lopez  luislopez@gmail.com    28  25000.0  Valencia     No

In [ ]:
#para entender como funciona la funcion dropna() vamos a usar una sintaxis
#mas completa y vemos que nos da el mismo resultado que antes. 'axis' puede ser
#igual a  'index' para referirse a filas o a 'columns' para referirse a columnas
#'how' puede ser 'any' es decir con que haya una sola celda con None elimina toda
#la fila o columna y 'how' tambien puede ser 'all' en cuyo caso solo elimina
#la fila o la columna si todas las celdas tienen None

df.dropna(axis='index', how='any')

  nombre apellido                email  edad  salario    ciudad casado
0  Marta     Ruiz  martaruiz@gmail.com    35  20000.0    Madrid    Yes
1   Luis    Lopez  luislopez@gmail.com    28  25000.0  Valencia     No

In [ ]:
df.dropna(axis='columns', how='any')

   edad
0    35
1    28
2    35
3    49
4    53
5    67

In [ ]:
df.dropna(axis='index', how='all')

   nombre apellido                  email  edad  salario    ciudad casado
0   Marta     Ruiz    martaruiz@gmail.com    35  20000.0    Madrid    Yes
1    Luis    Lopez    luislopez@gmail.com    28  25000.0  Valencia     No
2     Ana  Santana   anasantana@gmail.com    35      NaN    Malaga    Yes
3  Andres     None  andreslopez@gmail.com    49  17000.0     Cadiz     No
4    None   Castro                   None    53  20000.0    Burgos   None
5     Ana    Perez    saraperez@gmail.com    67  65000.0      None   None

In [ ]:
#vamos a eliminar filas o columnas que no tengan emails ya que consideramos
#imprescindible que tengan el email como minimo
#vamos a usar otro parametro que se llama 'subset'

df.dropna(axis='index', how='any', subset = ['email'])

   nombre apellido                  email  edad  salario    ciudad casado
0   Marta     Ruiz    martaruiz@gmail.com    35  20000.0    Madrid    Yes
1    Luis    Lopez    luislopez@gmail.com    28  25000.0  Valencia     No
2     Ana  Santana   anasantana@gmail.com    35      NaN    Malaga    Yes
3  Andres     None  andreslopez@gmail.com    49  17000.0     Cadiz     No
5     Ana    Perez    saraperez@gmail.com    67  65000.0      None   None

In [ ]:
#podemos pasarle varias columnas a la funcion 'subset'
df.dropna(axis='index', how='any', subset = ['email', 'casado'])

   nombre apellido                  email  edad  salario    ciudad casado
0   Marta     Ruiz    martaruiz@gmail.com    35  20000.0    Madrid    Yes
1    Luis    Lopez    luislopez@gmail.com    28  25000.0  Valencia     No
2     Ana  Santana   anasantana@gmail.com    35      NaN    Malaga    Yes
3  Andres     None  andreslopez@gmail.com    49  17000.0     Cadiz     No

In [ ]:
#si tanto email como casado tiene que ser None entonces usaremos
#el how='all'

df.dropna(axis='index', how='all', subset = ['email', 'casado'])

   nombre apellido                  email edad salario    ciudad casado
0   Marta     Ruiz    martaruiz@gmail.com   35   20000    Madrid    Yes
1    Luis    Lopez    luislopez@gmail.com   28   25000  Valencia     No
2     Ana  Santana   anasantana@gmail.com   35    None    Malaga    Yes
3  Andres    Lopez  andreslopez@gmail.com   49   17000     Cadiz     No
5     Ana    Perez    saraperez@gmail.com   67   65000    Madrid   None

In [ ]:
import pandas as pd

gentelimp2={
    'nombre': ['Marta', 'Luis', 'Ana', 'Andres', None, 'Ana'],
    'apellido': ['Ruiz', 'Lopez', 'Santana', None, 'Castro', 'Perez'],
    'email': ['martaruiz@gmail.com', 'luislopez@gmail.com', 'anasantana@gmail.com', 'andreslopez@gmail.com', None, 'saraperez@gmail.com'],
    'edad': [35, 28, 35, 49, 53, 67],
    'salario': [20000, 25000, None, 17000, 20000, 65000],
    'ciudad' :['Madrid', 'Valencia', 'Malaga', 'Cadiz', 'Burgos', None],
    'casado': ['Yes', 'No', 'Yes', 'No','Missing', 'None']
}

In [ ]:
df=pd.DataFrame(gentelimp2)

df

   nombre apellido                  email  edad  salario    ciudad   casado
0   Marta     Ruiz    martaruiz@gmail.com    35  20000.0    Madrid      Yes
1    Luis    Lopez    luislopez@gmail.com    28  25000.0  Valencia       No
2     Ana  Santana   anasantana@gmail.com    35      NaN    Malaga      Yes
3  Andres     None  andreslopez@gmail.com    49  17000.0     Cadiz       No
4    None   Castro                   None    53  20000.0    Burgos  Missing
5     Ana    Perez    saraperez@gmail.com    67  65000.0      None     None

In [ ]:
#si queremos substituir los 'Missing' y los 'NA' por None lo
#podemos hacer asi
df.replace('na', None)
df.replace('Missing', None)

   nombre apellido                  email  edad  salario    ciudad casado
0   Marta     Ruiz    martaruiz@gmail.com    35  20000.0    Madrid    Yes
1    Luis    Lopez    luislopez@gmail.com    28  25000.0  Valencia     No
2     Ana  Santana   anasantana@gmail.com    35      NaN    Malaga    Yes
3  Andres     None  andreslopez@gmail.com    49  17000.0     Cadiz     No
4    None   Castro                   None    53  20000.0    Burgos   None
5     Ana    Perez    saraperez@gmail.com    67  65000.0      None   None

In [ ]:
#si queremos ver que celdas tienen datos faltantes o extraños podemos
#usar la funcion isna()

df.isna()

   nombre  apellido  email   edad  salario  ciudad  casado
0   False     False  False  False    False   False   False
1   False     False  False  False    False   False   False
2   False     False  False  False     True   False   False
3   False      True  False  False    False   False   False
4    True     False   True  False    False   False   False
5   False     False  False  False    False    True   False

In [ ]:
#si queremos llenar los None (que previamente, hemos cambiado con el replace
#no olvidar inplace=True),
#con algun tipo de datos por ejemplo con NO SABE NO CONTESTA. usamos la funcion
#fillna()


df.fillna('NSNC')

   nombre apellido                  email  edad  salario    ciudad   casado
0   Marta     Ruiz    martaruiz@gmail.com    35  20000.0    Madrid      Yes
1    Luis    Lopez    luislopez@gmail.com    28  25000.0  Valencia       No
2     Ana  Santana   anasantana@gmail.com    35     NSNC    Malaga      Yes
3  Andres     NSNC  andreslopez@gmail.com    49  17000.0     Cadiz       No
4    NSNC   Castro                   NSNC    53  20000.0    Burgos  Missing
5     Ana    Perez    saraperez@gmail.com    67  65000.0      NSNC     None

In [ ]:

#otra cosa que podemos hacer es ver si nuestras celdas tienen un string
#o un integer, es decir queremos saber el tipo de dato. object es lo
#mismo que string en Pandas

df.dtypes

nombre       object
apellido     object
email        object
edad          int64
salario     float64
ciudad       object
casado       object
dtype: object

In [ ]:
df['edad']=df['edad'].astype(int)

In [ ]:
#podiamos haberlo cambiado a un float tambien
df.dtypes

nombre       object
apellido     object
email        object
edad          int64
salario     float64
ciudad       object
casado       object
dtype: object

In [ ]:
#ahora podemos calcular la media de edad de la DF

df['edad'].mean()

44.5

In [ ]:
#existe otra funcion unique() para saber cuantos diferentes tipos de datos puede
#tener una columna por ejemplo, vamos a verlo para la columna 'casado'
df['casado'].unique()

array(['Yes', 'No', None], dtype=object)

# UNIDAD 10. PREPROCESAMIENTO DE DATOS

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_excel('TITANIC.xlsx')

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,712833.00,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7925.00,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.05,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
#Verificar los valores faltantes

print(df.isnull(). sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
#Llenar los valores faltantes de 'Age' con la mediana de 'Age'

df.median()

<ipython-input-9-6d467abf240d>:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.median()

PassengerId    446.0
Survived         0.0
Pclass           3.0
Age             28.0
SibSp            0.0
Parch            0.0
Fare            71.0
dtype: float64

In [ ]:
df['Age']. median()

28.0

In [ ]:
df['Age'].fillna(df['Age'].median(), inplace=True)

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,712833.00,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7925.00,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.05,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
#Llenar los valores faltantes de 'Embarked' con el puerto de embarque más común

puerto_mas_comun= df['Embarked'].mode()[0]

puerto_mas_comun

'S'

In [ ]:
df['Embarked'].fillna(puerto_mas_comun, inplace=True)

df['Embarked']

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [ ]:
# Si decides trabajar con los datos disponibles de Cabin, podrías extraer la
# primera letra de cada valor de cabina para clasificar a los pasajeros por
# cubierta, y tratar los valores faltantes como una categoría aparte. Esto reduce
# la granularidad de los datos pero conserva información potencialmente útil sobre
# la ubicación del pasajero en el barco.

# Al usar .str[0], se está extrayendo el primer carácter de cada cadena en la
# columna Cabin.

df['Deck'] = df['Cabin'].str[0].fillna('Unknown')

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Deck
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S,Unknown
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,712833.00,C85,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7925.00,NaN,S,Unknown
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.10,C123,S,C
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.05,NaN,S,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S,Unknown
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S,B
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.45,NaN,S,Unknown
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q,Unknown

In [ ]:
print(df['Sex'].unique())

['male' 'female']

In [ ]:
#Vamos a convertir variables categoricas a variables numericas ya que en
#el campo de la ciencia de datos y de la inteligencia artificial asi se prefiere


df['Sex'] = df['Sex'].replace({'female':1, 'male':0})

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Deck
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.25,NaN,S,Unknown
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,712833.00,C85,C,C
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7925.00,NaN,S,Unknown
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.10,C123,S,C
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.05,NaN,S,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.0,0,0,211536,13.00,NaN,S,Unknown
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.0,0,0,112053,30.00,B42,S,B
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,28.0,1,2,W./C. 6607,23.45,NaN,S,Unknown
889,890,1,1,"Behr, Mr. Karl Howell",0,26.0,0,0,111369,30.00,C148,C,C
890,891,0,3,"Dooley, Mr. Patrick",0,32.0,0,0,370376,7.75,NaN,Q,Unknown

In [ ]:
#Convertir 'Embarked' en variables dummies

# Una variable dummy, también conocida como variable indicadora, es una variable
# binaria (0 o 1) que se utiliza para representar la presencia o ausencia de
# alguna categoría. La transformación de variables categóricas en variables dummy
# permite incluir información categórica en modelos que solo aceptan datos
# numéricos, manteniendo la interpretabilidad de los modelos.

embarcar_dummies = pd.get_dummies(df['Embarked'], prefix='Embarked')

df = pd.concat([df, embarcar_dummies], axis=1)

In [ ]:
print(df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Deck', 'Embarked_C', 'Embarked_Q',
       'Embarked_S'],
      dtype='object')

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Deck,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.25,NaN,Unknown,0,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,712833.00,C85,C,1,0,0
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7925.00,NaN,Unknown,0,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.10,C123,C,0,0,1
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.05,NaN,Unknown,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.0,0,0,211536,13.00,NaN,Unknown,0,0,1
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.0,0,0,112053,30.00,B42,B,0,0,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,28.0,1,2,W./C. 6607,23.45,NaN,Unknown,0,0,1
889,890,1,1,"Behr, Mr. Karl Howell",0,26.0,0,0,111369,30.00,C148,C,1,0,0
890,891,0,3,"Dooley, Mr. Patrick",0,32.0,0,0,370376,7.75,NaN,Unknown,0,1,0

In [ ]:
#Vamos a normalizar o escalar los valores de 'Fare' pagadas por los pasajeros

# Calcular el mínimo y máximo de la columna 'Fare'
fare_min = df['Fare'].min()
fare_max = df['Fare'].max()

In [ ]:
print(fare_min)
print(fare_max)

0.0
5123292.0

In [ ]:
# Aplicar la normalización Min-Max
df['Fare_Normalized'] = (df['Fare'] - fare_min) / (fare_max - fare_min)

In [ ]:
df['Fare_Normalized']

0      0.000001
1      0.139136
2      0.001547
3      0.000010
4      0.000002
         ...
886    0.000003
887    0.000006
888    0.000005
889    0.000006
890    0.000002
Name: Fare_Normalized, Length: 891, dtype: float64

In [ ]:
#Ingenieria de caracteristicas. Es comun crear nuevas caracteristicas que por
#ejemplo son combinacion de otras caracteristicas originales

# + 1 al final: Después de sumar SibSp y Parch, se añade 1 al resultado. Esto se
# hace para contar al propio pasajero en el tamaño de la familia. Por tanto, si
# un pasajero viaja solo, sin hermanos, cónyuges, padres o hijos, su TamañoFamilia
# será 1.

df['TamañoFamilia'] = df['SibSp'] + df['Parch'] + 1

In [ ]:
#Creamos una caracteristica 'ViajaSolo' para pasajeros que viajan solos

# En el contexto del Titanic, saber si un pasajero viajaba solo o con familiares
# podría influir en su probabilidad de supervivencia.

df['ViajaSolo'] = 1   #viaja solo
df['ViajaSolo'].loc[df['TamañoFamilia']>1]=0   #no viaja solo

<ipython-input-53-5ef5a2ee1359>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ViajaSolo'].loc[df['TamañoFamilia']>1]=0   #no viaja solo

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Deck,Embarked_C,Embarked_Q,Embarked_S,Fare_Normalized,TamañoFamilia,ViajaSolo
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.25,NaN,Unknown,0,0,1,0.000001,2,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,712833.00,C85,C,1,0,0,0.139136,2,0
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7925.00,NaN,Unknown,0,0,1,0.001547,1,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.10,C123,C,0,0,1,0.000010,2,0
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.05,NaN,Unknown,0,0,1,0.000002,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.0,0,0,211536,13.00,NaN,Unknown,0,0,1,0.000003,1,1
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.0,0,0,112053,30.00,B42,B,0,0,1,0.000006,1,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,28.0,1,2,W./C. 6607,23.45,NaN,Unknown,0,0,1,0.000005,4,0
889,890,1,1,"Behr, Mr. Karl Howell",0,26.0,0,0,111369,30.00,C148,C,1,0,0,0.000006,1,1
890,891,0,3,"Dooley, Mr. Patrick",0,32.0,0,0,370376,7.75,NaN,Unknown,0,1,0,0.000002,1,1

# UNIDAD 11. ANALISIS DE DATOS DEL TITANIC

In [ ]:
data = pd.read_csv('titanic_train.csv')

data.head(7)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S

In [ ]:
#Que pasajeros que embarcaron en el puerto C pagaron mas de 200 libras por el ticket

data[(data['Embarked']=='C') & (data['Fare'] > 200)].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0,0,1,PC 17558,247.5208,B58 B60,C
311,312,1,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
377,378,0,1,"Widener, Mr. Harry Elkins",male,27.0,0,2,113503,211.5000,C82,C

In [ ]:
#Cuantos hombres y cuantas mujeres iban abordo

data['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [ ]:
#Cuantos hombres en segunda clase iban abordo

total = (data['Sex'] == "male") & (data['Pclass'] == 2)
suma = total.sum()

In [ ]:
suma

108

In [ ]:
#Cuales son la media y la desviacion standard de Fare

data['Fare'].mean()

32.204207968574636

In [ ]:
data['Fare'].std()

49.6934285971809

In [ ]:
#La media de edad de los supervivinetes es mayor que la media de edad de los fallecidos?

In [ ]:
data[data['Survived'] == 0].Age.mean()

30.62617924528302

In [ ]:
data[data['Survived'] == 1].Age.mean()

28.343689655172415

In [ ]:
#Otra tecnica para calcularlo
data.groupby('Survived')['Age'].mean()

Survived
0    30.626179
1    28.343690
Name: Age, dtype: float64

In [ ]:
#Cual es el porcentaje de pasajeros supervivientes mayores de 60 y menores de 30

joven = data[data['Age']<30]

In [ ]:
joven.Survived.mean()

0.40625

In [ ]:
senior=data[data['Age']>60]

In [ ]:
senior.Survived.mean()

0.22727272727272727

In [ ]:
#Cual es el porcentaje de hombres y mujeres que sobrevivieron

women = data[data['Sex']=="female"]
men   = data[data['Sex']=="male"]

In [ ]:
print(women.Survived.mean())
print(men.Survived.mean())

0.7420382165605095
0.18890814558058924

In [ ]:
#Otra tecnica

data.groupby('Sex')['Survived'].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64